# Use a Node.js base image
FROM node:alpine as build

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Build the React application
RUN npm run build

# Use a lightweight Nginx image for serving
FROM nginx:alpine

# Copy the build output from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
# EXPOSE 80
# Start Nginx
# CMD ["nginx", "-g", "daemon off;"]

# Use the custom nginx configuration
COPY default.conf /etc/nginx/conf.d/default.conf

# Expose Cloud Run's expected port, typically 8080
EXPOSE 8080

# Start nginx with PORT substitution
CMD ["sh", "-c", "envsubst '${PORT}' < /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

